<?php

use Taxonomia\Model\Category;
use Taxonomia\Model\CategoryItem;

$category = new Category();

$category->setId(1);
$category->setName("Wurzel");
$category->isLowestLevel(true);

$model->searchTriples(
   ['s' => ['concept' => 'is a'],
    'p' => ['concept' => 'every'],
    'o' => ['concept' => 'language']],
   function ($row) use ($model,$category) {
       $item = new CategoryItem();
       $item->setId($row['id']);
       $item->setName('Alle Sprachen');
       $item->setHasChildren(true);
       $category->addItem($item);
   });

$model->searchTriples(
   ['p' => ['concept' => 'is a'],'o' => ['concept' => 'language']],
   function ($row) use ($model,$category) {
       $item = new CategoryItem();
       $item->setId($row['id']);
       $item->setName($model->getConcept($row['s']));
       $item->setHasChildren(true);
       $category->addItem($item);
   });

echo json_encode($category,JSON_PRETTY_PRINT);

return;
