<?php

use Taxonomia\Model\Category;
use Taxonomia\Model\CategoryItem;

// die(print_r($_SESSION));

$folder = basename($triple['o']['value']);

$category = new Category();

$category->setId($triple['s']['id']);
$category->setName($folder);
$category->setParentId($triple['o']['id']);

$model->lockCreation();
$topic['is a'] = $model->concept('is a');
$topic['document'] = $model->concept('document');
$model->unlockCreation();

$doccount = $model->countTriples(
           ['s' => $triple['o']['id'],
            'p' => $topic['is a'],
            'o' => $topic['document']]);
if($doccount == 1) {
    echo json_encode($category,JSON_PRETTY_PRINT);
    return;
}

// search in folder
$model->searchTriples(
   ['s' => $triple['o']['id'], 'p' => ['concept' => 'contains']],
   function ($row) use ($model,$category,$num,$topic) {
       $triple = $model->getTriple($row['id']);
       $item = new CategoryItem();
       $item->setId($row['id']);
       $item->setName(basename($triple['o']['value']));
       $item->setParentId($num);
       $doccount = $model->countTriples(
           ['s' => $triple['o']['id'],
            'p' => $topic['is a'],
            'o' => $topic['document']]);
       $item->setHasChildren($doccount < 1);
       $category->addItem($item);
   });

echo json_encode($category,JSON_PRETTY_PRINT);

return;
