<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./miller/css/miller.css"/>
    <link rel="stylesheet" href="./miller/css/miller-material.css"/>
    <link rel="stylesheet" href="./miller/css/material-design-font-style.css"/>

    <link rel="stylesheet" href="./miller/demo/css/demo.css"/>
    <link rel="stylesheet" href="./miller/demo/css/simple-dropdown.css"/>

    <script type="text/javascript" src="miller/js/jquery.js"></script>
    <script type="text/javascript" src="miller/js/miller.js"></script>

    <script type="text/javascript" src="miller/demo/js/simple-popup.min.js"></script>
    <script type="text/javascript" src="js/taxonomia.js"></script>
    <script type="text/javascript" src="miller/demo/js/simple-dropdown.js"></script>
</head>

<body>

<div class="switch demo3">
    <h3>Editable?</h3>
    <input type="checkbox" id="read_only_input" value="off">
    <label><i></i></label>
</div>

<div id="category-miller-cols-container">
</div>

<pre>
<?php // print_r($db); ?>
</pre>
</body>

</html>
