<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./miller/css/miller.css"/>
    <link rel="stylesheet" href="./miller/css/miller-material.css"/>
    <link rel="stylesheet" href="./miller/css/material-design-font-style.css"/>
    <link rel="stylesheet" href="./style.css"/>
</head>

<body>

<div class="main-tabs">

  <h2>Taxonomia</h2>
  <div class="panel tabbody">
      <div id="category-miller-cols-container">
      </div>

      <div id="word-cloud-container">test
      </div>

      <div id="item-actions-container">
      </div>
  </div>

</div>

<pre>
<?php // print_r($db); ?>
</pre>

<script type="text/javascript" data-main="main.js" src="./js/require.js"></script>

</body>

</html>
