<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./miller/css/miller.css"/>
    <link rel="stylesheet" href="./miller/css/miller-material.css"/>
    <link rel="stylesheet" href="./miller/css/material-design-font-style.css"/>
    <link rel="stylesheet" href="./style.css"/>

    <script type="text/javascript" src="./miller/js/jquery.js"></script>
    <script type="text/javascript" src="./miller/js/miller.js"></script>

    <script type="text/javascript" src="./js/taxonomia.js"></script>
</head>

<body>

<div id="category-miller-cols-container">
</div>

<div id="word-cloud-container">
</div>

<div id="item-actions-container">
</div>

<pre>
<?php // print_r($db); ?>
</pre>
</body>

</html>
